// Generated by translation-codegen
export type TranslationKey =
  | 'screen.camera.permissions.title'
  | 'screen.camera.permissions.sections.how_to_use.title'
  | 'screen.camera.permissions.sections.how_to_use.description'
  | 'screen.camera.permissions.sections.how_we_use.title'
  | 'screen.camera.permissions.sections.how_we_use.description'
  | 'screen.camera.permissions.sections.settings.title'
  | 'screen.camera.permissions.sections.settings.description'
  | 'screen.camera.permissions.actions.continue'
